[package]
name = "sdl2-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.36.0", features = ["ttf"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
